services:
  clickhouse:
    build:
      context: ./docker/clickhouse/
      args:
        TAG: 24.8.4.13-alpine@sha256:88a45f9e328549b2579256c46ee38e5c0e25ae58303d9eb6d9c7ed8d6d2bbf3c
    container_name: "clickhouse"
    hostname: clickhouse
    restart: always
    environment:
      CLICKHOUSE_DB: "${CLICKHOUSE_DB:-default}"
      CLICKHOUSE_USER: "${CLICKHOUSE_USER:-default}"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD?CLICKHOUSE_PASSWORD_is_not_set}"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT:-0}"
    volumes:
      - ./input_data:/csv_files
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    networks:
      - db

  worker:
    build:
      context: ./worker/
      dockerfile: ../docker/worker/Dockerfile
      args: 
        TAG: 3.12-slim
    hostname: worker
    container_name: worker
    depends_on:
      - clickhouse
    environment:
      PROCESSING_LIMIT: ${PROCESSING_LIMIT:-6000000}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB:?CLICKHOUSE_DB_is_not_set}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:?CLICKHOUSE_USER_is_not_set}
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD?CLICKHOUSE_PASSWORD_is_not_set}"
      CLICKHOUSE_HOST: "${CLICKHOUSE_HOST:?CLICKHOUSE_HOST_is_not_set}"
      CLICKHOUSE_PORT: "${CLICKHOUSE_PORT?:CLICKHOUSE_PORT_is_not_set}"
    networks:
      - db

networks:
  db:
    name: "db"
    driver: bridge
